version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  generator:
    build: ./generator
    depends_on:
      - db

  redash:
    image: redash/redash:latest
    ports:
      - "5000:5000"
    environment:
      REDASH_DATABASE_URL: "postgresql://user:password@db/analytics_db"